const touristPlace= [
    {name:'Glacier Walk Combo', description:'Get the best bang for your buck by combining a kayaking tour on the Sólheimajökull glacier lagoon with a Glacier Walk. After meeting your expert guide at the Sólheimajökull Base next to the Sólheimajökull.', time:'5 Days / 6 Nights', rating:5, price:1610.00,img:'https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2019/11/13/51cbd6b4-3dd3-43fa-b310-8202adf8da05/mendenhall-glacier', id:1},

    {name:'The Splendor Of Manali', description:"It's very near to manu temple (Manali is named after the Brahmin lawgiver Manu). The word Manali is regarded as the changed name of Manu-Alaya which literally means the abode of Manu.", time:'5 Days / 6 Nights', rating:5, price:470.00,img:'https://imgcld.yatra.com/ytimages/image/upload/t_holidays_srplist_tablet_hc/v1484282643/Manali_overview1.jpg', id:2},

    {name:"Sajek Valley - BD", description:"Sajek Valley is one of the popular tourist spots in Bangladesh situated among the hills of the Kasalong range of mountains in Sajek union, Baghaichhari Upazila in Rangamati District. Sajek valley is known as the Queen of Hills & Roof of Rangamati.", time:'2 Days / 3 Nights', rating:5, price:700.00, img:'https://www.thesatourism.com/wp-content/uploads/2017/01/Sajek-valley-1.jpg', id:3},

    {name:'Great Britain Travel', description:'Explore history you can touch as you wander the ornate halls of  the footsteps of clans and kings in Edinburgh. Find stories you’ll share,Liverpool Biennial or grand Old Masters in London’s National Gallery.', time:'5 Days / 6 Nights', rating:5, price:820.00,img:"https://imgproxy.natucate.com/e9H97jMu4UKYa2GXXzLj3I_CZxi45elu2gAYHe-3ong/rs:fill/g:ce/w:3840/h:2160/aHR0cHM6Ly93d3cubmF0dWNhdGUuY29tL21lZGlhL3BhZ2VzL3JlaXNlemllbGUvZDM0MTBkYTMtZWM4Yi00ODM5LTgzYzYtMWNkM2M3OGNlNDgzLzMzNDU5NDYwMjEtMTU1OTY1OTM2OC9ncm9zc2JyaXRhbm5pZW4tdWstbGFlbmRlcmluZm9ybWF0aW9uZW4tYnJ1ZWNrZS10b3dlci1icmlkZ2UtbG9uZG9uLW5hdHVjYXRlLmpwZw", id:4},

    {name:'Beauty Of Taj-Mahal', description:'The Taj Mahal is widely considered one of the most beautiful buildings ever created. The exquisite marble structure in Agra, India, is a mausoleum, an enduring monument to the love of a husband for his favorite wife.', time:'4 Days / 5 Nights', rating:5, price:1170.00,img:'http://1.bp.blogspot.com/-0DU4SaLdB58/U2n6YaF7LQI/AAAAAAAACdg/mVSW85V3D6E/s1600/Taj-Mahal-Agra.jpg', id:5},

    {name:'Venice Tour - Italy', description:"Explore Venice by boat and by foot on this city discovery tour and gondola ride. Highlighted sites include Saint Mark's Basilica, the Doge's Palace, the Bridge of Sighs, Campo Santa Maria Formosa, La Fenice Opera House.", time:'3 Days / 4 Nights', rating:5, price:980.00, img:'https://www.shoreexcursionsgroup.com/img/tour/EUVCTGRIDE-2C.jpg', id:6},

    {name:'Super Maldives Trip', description:"One of the best places to visit in Maldives. Locations breathtaking.The resort is very clean is prompt. Enjoyed different kinds of food in restaurant. They will inform you in advance if you are taking any extra services", time:'5 Days / 6 Nights', rating:5, price:1020.00, img:'https://static01.nyt.com/images/2021/08/05/travel/05Maldives1/05Maldives1-superJumbo.jpg', id:7},

    {name:"'Cox's Bazar - BD", description:"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues .", time:'3 Days / 4 Nights', rating:5, price:1080.00, img:'https://i.ytimg.com/vi/jZ4OSWdQXFE/maxresdefault.jpg', id:8},

    {name:"Great Wall of China", description:"The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe.", time:'5 Days / 6 Nights', rating:5, price:980.00, img:'https://cdn.britannica.com/s:800x450,c:crop/89/179589-138-3EE27C94/Overview-Great-Wall-of-China.jpg', id:9},
]